server:
  port: 8080
#es http方式
elasticsearch:
  address: 192.168.181.128:9200,192.168.181.129:9200,192.168.181.130:9200
#  username: admin
#  password: admin

# swagger2
swagger2.package: com.example.esdemo.controller
springfox.documentation.swagger.v2.path: /api-docs